/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdminSideMenu: typeof import('./../../src/components/adminSideMenu/adminSideMenu.vue')['default']
    Base: typeof import('./../../src/components/adminFormItem/base.vue')['default']
    Cascader: typeof import('./../../src/components/cascader.vue')['default']
    Device_1: typeof import('./../../src/components/login/components/device_1.vue')['default']
    Device_2: typeof import('./../../src/components/login/components/device_2.vue')['default']
    Device_3: typeof import('./../../src/components/login/components/device_3.vue')['default']
    Device_4: typeof import('./../../src/components/login/components/device_4.vue')['default']
    Dialog: typeof import('./../../src/components/dialog/Dialog.vue')['default']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCascader: typeof import('element-plus/es')['ElCascader']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTimePicker: typeof import('element-plus/es')['ElTimePicker']
    ElTree: typeof import('element-plus/es')['ElTree']
    Flex: typeof import('./../../src/components/flex/Flex.vue')['default']
    FormItem: typeof import('./../../src/components/adminFormItem/formItem.vue')['default']
    HelloWorld: typeof import('./../../src/components/HelloWorld.vue')['default']
    LbRender: typeof import('./../../src/components/adminPage-table/lb-render.vue')['default']
    Line: typeof import('./../../src/components/login/components/line.vue')['default']
    Login: typeof import('./../../src/components/login/login.vue')['default']
    Main: typeof import('./../../src/components/adminView/main.vue')['default']
    OtherBtnList: typeof import('./../../src/components/adminSearchForm/otherBtnList.vue')['default']
    PageTable: typeof import('./../../src/components/adminPage-table/PageTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchForm: typeof import('./../../src/components/adminSearchForm/searchForm.vue')['default']
    Tabs: typeof import('./../../src/components/tabs/tabs.vue')['default']
    Tree: typeof import('./../../src/components/tree/tree.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
